<!doctype html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />

    <title>honeybeex.revit API documentation</title>
    <meta name="description" content="Collection of functions for Revit." />

  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300' rel='stylesheet' type='text/css'>

  <!-- highlight.js for highlighting source code. -->
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/styles/default.min.css">
  <script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/highlight.min.js"></script>

  
  <style type="text/css">
  
* {
  box-sizing: border-box;
}
/*! normalize.css v1.1.1 | MIT License | git.io/normalize */

/* ==========================================================================
   HTML5 display definitions
   ========================================================================== */

/**
 * Correct `block` display not defined in IE 6/7/8/9 and Firefox 3.
 */

article,
aside,
details,
figcaption,
figure,
footer,
header,
hgroup,
main,
nav,
section,
summary {
    display: block;
}

/**
 * Correct `inline-block` display not defined in IE 6/7/8/9 and Firefox 3.
 */

audio,
canvas,
video {
    display: inline-block;
    *display: inline;
    *zoom: 1;
}

/**
 * Prevent modern browsers from displaying `audio` without controls.
 * Remove excess height in iOS 5 devices.
 */

audio:not([controls]) {
    display: none;
    height: 0;
}

/**
 * Address styling not present in IE 7/8/9, Firefox 3, and Safari 4.
 * Known issue: no IE 6 support.
 */

[hidden] {
    display: none;
}

/* ==========================================================================
   Base
   ========================================================================== */

/**
 * 1. Prevent system color scheme's background color being used in Firefox, IE,
 *    and Opera.
 * 2. Prevent system color scheme's text color being used in Firefox, IE, and
 *    Opera.
 * 3. Correct text resizing oddly in IE 6/7 when body `font-size` is set using
 *    `em` units.
 * 4. Prevent iOS text size adjust after orientation change, without disabling
 *    user zoom.
 */

html {
    background: #fff; /* 1 */
    color: #000; /* 2 */
    font-size: 100%; /* 3 */
    -webkit-text-size-adjust: 100%; /* 4 */
    -ms-text-size-adjust: 100%; /* 4 */
}

/**
 * Address `font-family` inconsistency between `textarea` and other form
 * elements.
 */

html,
button,
input,
select,
textarea {
    font-family: sans-serif;
}

/**
 * Address margins handled incorrectly in IE 6/7.
 */

body {
    margin: 0;
}

/* ==========================================================================
   Links
   ========================================================================== */

/**
 * Address `outline` inconsistency between Chrome and other browsers.
 */

a:focus {
    outline: thin dotted;
}

/**
 * Improve readability when focused and also mouse hovered in all browsers.
 */

a:active,
a:hover {
    outline: 0;
}

/* ==========================================================================
   Typography
   ========================================================================== */

/**
 * Address font sizes and margins set differently in IE 6/7.
 * Address font sizes within `section` and `article` in Firefox 4+, Safari 5,
 * and Chrome.
 */

h1 {
    font-size: 2em;
    margin: 0.67em 0;
}

h2 {
    font-size: 1.5em;
    margin: 0.83em 0;
}

h3 {
    font-size: 1.17em;
    margin: 1em 0;
}

h4 {
    font-size: 1em;
    margin: 1.33em 0;
}

h5 {
    font-size: 0.83em;
    margin: 1.67em 0;
}

h6 {
    font-size: 0.67em;
    margin: 2.33em 0;
}

/**
 * Address styling not present in IE 7/8/9, Safari 5, and Chrome.
 */

abbr[title] {
    border-bottom: 1px dotted;
}

/**
 * Address style set to `bolder` in Firefox 3+, Safari 4/5, and Chrome.
 */

b,
strong {
    font-weight: bold;
}

blockquote {
    margin: 1em 40px;
}

/**
 * Address styling not present in Safari 5 and Chrome.
 */

dfn {
    font-style: italic;
}

/**
 * Address differences between Firefox and other browsers.
 * Known issue: no IE 6/7 normalization.
 */

hr {
    -moz-box-sizing: content-box;
    box-sizing: content-box;
    height: 0;
}

/**
 * Address styling not present in IE 6/7/8/9.
 */

mark {
    background: #ff0;
    color: #000;
}

/**
 * Address margins set differently in IE 6/7.
 */

p,
pre {
    margin: 1em 0;
}

/**
 * Correct font family set oddly in IE 6, Safari 4/5, and Chrome.
 */

code,
kbd,
pre,
samp {
    font-family: monospace, serif;
    _font-family: 'courier new', monospace;
    font-size: 0.9em;
}

/**
 * Improve readability of pre-formatted text in all browsers.
 */

pre {
    white-space: pre;
    white-space: pre-wrap;
    word-wrap: break-word;
}

/**
 * Address CSS quotes not supported in IE 6/7.
 */

q {
    quotes: none;
}

/**
 * Address `quotes` property not supported in Safari 4.
 */

q:before,
q:after {
    content: '';
    content: none;
}

/**
 * Address inconsistent and variable font size in all browsers.
 */

small {
    font-size: 80%;
}

/**
 * Prevent `sub` and `sup` affecting `line-height` in all browsers.
 */

sub,
sup {
    font-size: 75%;
    line-height: 0;
    position: relative;
    vertical-align: baseline;
}

sup {
    top: -0.5em;
}

sub {
    bottom: -0.25em;
}

/* ==========================================================================
   Lists
   ========================================================================== */

/**
 * Address margins set differently in IE 6/7.
 */

dl,
menu,
ol,
ul {
    margin: 1em 0;
}

dd {
    margin: 0 0 0 40px;
}

/**
 * Address paddings set differently in IE 6/7.
 */

menu,
ol,
ul {
    padding: 0 0 0 40px;
}

/**
 * Correct list images handled incorrectly in IE 7.
 */

nav ul,
nav ol {
    list-style: none;
    list-style-image: none;
}

/* ==========================================================================
   Embedded content
   ========================================================================== */

/**
 * 1. Remove border when inside `a` element in IE 6/7/8/9 and Firefox 3.
 * 2. Improve image quality when scaled in IE 7.
 */

img {
    border: 0; /* 1 */
    -ms-interpolation-mode: bicubic; /* 2 */
}

/**
 * Correct overflow displayed oddly in IE 9.
 */

svg:not(:root) {
    overflow: hidden;
}

/* ==========================================================================
   Figures
   ========================================================================== */

/**
 * Address margin not present in IE 6/7/8/9, Safari 5, and Opera 11.
 */

figure {
    margin: 0;
}

/* ==========================================================================
   Forms
   ========================================================================== */

/**
 * Correct margin displayed oddly in IE 6/7.
 */

form {
    margin: 0;
}

/**
 * Define consistent border, margin, and padding.
 */

fieldset {
    border: 1px solid #c0c0c0;
    margin: 0 2px;
    padding: 0.35em 0.625em 0.75em;
}

/**
 * 1. Correct color not being inherited in IE 6/7/8/9.
 * 2. Correct text not wrapping in Firefox 3.
 * 3. Correct alignment displayed oddly in IE 6/7.
 */

legend {
    border: 0; /* 1 */
    padding: 0;
    white-space: normal; /* 2 */
    *margin-left: -7px; /* 3 */
}

/**
 * 1. Correct font size not being inherited in all browsers.
 * 2. Address margins set differently in IE 6/7, Firefox 3+, Safari 5,
 *    and Chrome.
 * 3. Improve appearance and consistency in all browsers.
 */

button,
input,
select,
textarea {
    font-size: 100%; /* 1 */
    margin: 0; /* 2 */
    vertical-align: baseline; /* 3 */
    *vertical-align: middle; /* 3 */
}

/**
 * Address Firefox 3+ setting `line-height` on `input` using `!important` in
 * the UA stylesheet.
 */

button,
input {
    line-height: normal;
}

/**
 * Address inconsistent `text-transform` inheritance for `button` and `select`.
 * All other form control elements do not inherit `text-transform` values.
 * Correct `button` style inheritance in Chrome, Safari 5+, and IE 6+.
 * Correct `select` style inheritance in Firefox 4+ and Opera.
 */

button,
select {
    text-transform: none;
}

/**
 * 1. Avoid the WebKit bug in Android 4.0.* where (2) destroys native `audio`
 *    and `video` controls.
 * 2. Correct inability to style clickable `input` types in iOS.
 * 3. Improve usability and consistency of cursor style between image-type
 *    `input` and others.
 * 4. Remove inner spacing in IE 7 without affecting normal text inputs.
 *    Known issue: inner spacing remains in IE 6.
 */

button,
html input[type="button"], /* 1 */
input[type="reset"],
input[type="submit"] {
    -webkit-appearance: button; /* 2 */
    cursor: pointer; /* 3 */
    *overflow: visible;  /* 4 */
}

/**
 * Re-set default cursor for disabled elements.
 */

button[disabled],
html input[disabled] {
    cursor: default;
}

/**
 * 1. Address box sizing set to content-box in IE 8/9.
 * 2. Remove excess padding in IE 8/9.
 * 3. Remove excess padding in IE 7.
 *    Known issue: excess padding remains in IE 6.
 */

input[type="checkbox"],
input[type="radio"] {
    box-sizing: border-box; /* 1 */
    padding: 0; /* 2 */
    *height: 13px; /* 3 */
    *width: 13px; /* 3 */
}

/**
 * 1. Address `appearance` set to `searchfield` in Safari 5 and Chrome.
 * 2. Address `box-sizing` set to `border-box` in Safari 5 and Chrome
 *    (include `-moz` to future-proof).
 */

input[type="search"] {
    -webkit-appearance: textfield; /* 1 */
    -moz-box-sizing: content-box;
    -webkit-box-sizing: content-box; /* 2 */
    box-sizing: content-box;
}

/**
 * Remove inner padding and search cancel button in Safari 5 and Chrome
 * on OS X.
 */

input[type="search"]::-webkit-search-cancel-button,
input[type="search"]::-webkit-search-decoration {
    -webkit-appearance: none;
}

/**
 * Remove inner padding and border in Firefox 3+.
 */

button::-moz-focus-inner,
input::-moz-focus-inner {
    border: 0;
    padding: 0;
}

/**
 * 1. Remove default vertical scrollbar in IE 6/7/8/9.
 * 2. Improve readability and alignment in all browsers.
 */

textarea {
    overflow: auto; /* 1 */
    vertical-align: top; /* 2 */
}

/* ==========================================================================
   Tables
   ========================================================================== */

/**
 * Remove most spacing between table cells.
 */

table {
    border-collapse: collapse;
    border-spacing: 0;
}

  </style>

  <style type="text/css">
  
  html, body {
    margin: 0;
    padding: 0;
    min-height: 100%;
  }
  body {
    background: #fff;
    font-family: "Source Sans Pro", "Helvetica Neueue", Helvetica, sans;
    font-weight: 300;
    font-size: 16px;
    line-height: 1.6em;
  }
  #content {
    width: 70%;
    margin-left: 25%;
    max-width: 90%;
    float: left;
    padding: 30px 60px;
    border-left: 1px solid #ddd;
  }
  #sidebar {
    position: fixed;
    height: 100%;
    width: 25%;
    float: left;
    padding: 30px;
    overflow-x: hidden;
    overflow-y: auto;
  }
  #nav {
    font-size: 130%;
    margin: 0 0 15px 0;
  }

  #top {
    display: block;
    position: fixed;
    bottom: 5px;
    left: 5px;
    font-size: .85em;
    text-transform: uppercase;
  }

  #footer {
    font-size: .75em;
    padding: 5px 30px;
    border-top: 1px solid #ddd;
    text-align: right;
  }
    #footer p {
      margin: 0 0 0 30px;
      display: inline-block;
    }

  h1, h2, h3, h4, h5 {
    font-weight: 300;
  }
  h1 {
    font-size: 2.5em;
    line-height: 1.1em;
    margin: 0 0 .50em 0;
  }

  h2 {
    font-size: 1.75em;
    margin: 1em 0 .50em 0;
  }

  h3 {
    margin: 25px 0 10px 0;
  }

  h4 {
    margin: 0;
    font-size: 105%;
  }

  a {
    color: #058;
    text-decoration: none;
    transition: color .3s ease-in-out;
  }

  a:hover {
    color: #e08524;
    transition: color .3s ease-in-out;
  }

  pre, code, .mono, .name {
    font-family: "Ubuntu Mono", "Cousine", "DejaVu Sans Mono", monospace;
  }

  .title .name {
    font-weight: bold;
  }
  .section-title {
    margin-top: 2em;
  }
  .ident {
    color: #900;
  }

  pre {
    background: #fefefe;
    border: 1px solid #ddd;
    box-shadow: 2px 2px 0 #f3f3f3;
    margin: 0 30px;
    padding: 15px 30px;
  }

  .codehilite {
    margin: 0 30px 10px 30px;
  }

    .codehilite pre {
      margin: 0;
    }
    .codehilite .err { background: #ff3300; color: #fff !important; }

  table#module-list {
    font-size: 110%;
  }

    table#module-list tr td:first-child {
      padding-right: 10px;
      white-space: nowrap;
    }

    table#module-list td {
      vertical-align: top;
      padding-bottom: 8px;
    }

      table#module-list td p {
        margin: 0 0 7px 0;
      }

  .def {
    display: table;
  }

    .def p {
      display: table-cell;
      vertical-align: top;
      text-align: left;
    }

    .def p:first-child {
      white-space: nowrap;
    }

    .def p:last-child {
      width: 100%;
    }


  #index {
    list-style-type: none;
    margin: 0;
    padding: 0;
  }
    ul#index .class_name {
      /* font-size: 110%; */
      font-weight: bold;
    }
    #index ul {
      margin: 0;
    }

  .item {
    margin: 0 0 15px 0;
  }

    .item .class {
      margin: 0 0 25px 30px;
    }

      .item .class ul.class_list {
        margin: 0 0 20px 0;
      }

    .item .name {
      background: #fafafa;
      margin: 0;
      font-weight: bold;
      padding: 5px 10px;
      border-radius: 3px;
      display: inline-block;
      min-width: 40%;
    }
      .item .name:hover {
        background: #f6f6f6;
      }

    .item .empty_desc {
      margin: 0 0 5px 0;
      padding: 0;
    }

    .item .inheritance {
      margin: 3px 0 0 30px;
    }

    .item .inherited {
      color: #666;
    }

    .item .desc {
      padding: 0 8px;
      margin: 0;
    }

      .item .desc p {
        margin: 0 0 10px 0;
      }

    .source_cont {
      margin: 0;
      padding: 0;
    }

    .source_link a {
      background: #ffc300;
      font-weight: 400;
      font-size: .75em;
      text-transform: uppercase;
      color: #fff;
      text-shadow: 1px 1px 0 #f4b700;

      padding: 3px 8px;
      border-radius: 2px;
      transition: background .3s ease-in-out;
    }
      .source_link a:hover {
        background: #FF7200;
        text-shadow: none;
        transition: background .3s ease-in-out;
      }

    .source {
      display: none;
      max-height: 600px;
      overflow-y: auto;
      margin-bottom: 15px;
    }

      .source .codehilite {
        margin: 0;
      }

  .desc h1, .desc h2, .desc h3 {
    font-size: 100% !important;
  }

  .desc {
    white-space: pre-wrap;
  }

  .clear {
    clear: both;
  }

  @media all and (max-width: 950px) {
    #sidebar {
        position: inherit;
        float: none;
        width: auto;
    }
    #content {
      width: 95%;
      margin-left: auto;
      border-left: none;
      padding: 30px;
    }
  }
  @media all and (max-width: 650px) {
    #top {
      display: none;
    }
    #sidebar {
      float: none;
      width: auto;
    }
    #content {
      float: none;
      width: auto;
      padding: 30px;
    }

    #index ul {
      padding: 0;
      margin-bottom: 15px;
    }
    #index ul li {
      display: inline-block;
      margin-right: 30px;
    }
    #footer {
      text-align: left;
    }
    #footer p {
      display: block;
      margin: inherit;
    }
  }

  /*****************************/

  </style>


  <style type="text/css">
  
/* ==========================================================================
   EXAMPLE Media Queries for Responsive Design.
   These examples override the primary ('mobile first') styles.
   Modify as content requires.
   ========================================================================== */

@media only screen and (min-width: 35em) {
    /* Style adjustments for viewports that meet the condition */
}

@media print,
       (-o-min-device-pixel-ratio: 5/4),
       (-webkit-min-device-pixel-ratio: 1.25),
       (min-resolution: 120dpi) {
    /* Style adjustments for high resolution devices */
}

/* ==========================================================================
   Print styles.
   Inlined to avoid required HTTP connection: h5bp.com/r
   ========================================================================== */

@media print {
    * {
        background: transparent !important;
        color: #000 !important; /* Black prints faster: h5bp.com/s */
        box-shadow: none !important;
        text-shadow: none !important;
    }

    a,
    a:visited {
        text-decoration: underline;
    }

    a[href]:after {
        content: " (" attr(href) ")";
    }

    abbr[title]:after {
        content: " (" attr(title) ")";
    }

    /*
     * Don't show links for images, or javascript/internal links
     */

    .ir a:after,
    a[href^="javascript:"]:after,
    a[href^="#"]:after {
        content: "";
    }

    pre,
    blockquote {
        border: 1px solid #999;
        page-break-inside: avoid;
    }

    thead {
        display: table-header-group; /* h5bp.com/t */
    }

    tr,
    img {
        page-break-inside: avoid;
    }

    img {
        max-width: 100% !important;
    }

    @page {
        margin: 0.5cm;
    }

    p,
    h2,
    h3 {
        orphans: 3;
        widows: 3;
    }

    h2,
    h3 {
        page-break-after: avoid;
    }
}

  </style>

  <script type="text/javascript">
  function toggle(id, $link) {
    $node = document.getElementById(id);
    if (!$node)
    return;
    if (!$node.style.display || $node.style.display == 'none') {
    $node.style.display = 'block';
    $link.innerHTML = 'Hide source &nequiv;';
    } else {
    $node.style.display = 'none';
    $link.innerHTML = 'Show source &equiv;';
    }
  }
  </script>
</head>
<body>
<a href="#" id="top">Top</a>

<div id="container">
    
  
  <div id="sidebar">
    <h1>Index</h1>
    <ul id="index">

    <li class="set"><h3><a href="#header-functions">Functions</a></h3>
      
  <ul>
    <li class="mono"><a href="#honeybeex.revit.collectMEPSpaces">collectMEPSpaces</a></li>
    <li class="mono"><a href="#honeybeex.revit.collectRooms">collectRooms</a></li>
    <li class="mono"><a href="#honeybeex.revit.convertRoomsToHBZones">convertRoomsToHBZones</a></li>
    <li class="mono"><a href="#honeybeex.revit.createUUID">createUUID</a></li>
    <li class="mono"><a href="#honeybeex.revit.exctractGlazingVertices">exctractGlazingVertices</a></li>
    <li class="mono"><a href="#honeybeex.revit.extractPanelsVertices">extractPanelsVertices</a></li>
    <li class="mono"><a href="#honeybeex.revit.getBoundaryLocation">getBoundaryLocation</a></li>
    <li class="mono"><a href="#honeybeex.revit.getChildElemenets">getChildElemenets</a></li>
    <li class="mono"><a href="#honeybeex.revit.getParameter">getParameter</a></li>
    <li class="mono"><a href="#honeybeex.revit.getParameters">getParameters</a></li>
  </ul>

    </li>


    </ul>
  </div>

    <article id="content">
      
  

  


  <header id="section-intro">
  <h1 class="title"><span class="name">honeybeex.revit</span> module</h1>
  <p>Collection of functions for Revit.</p>
  
  <p class="source_link"><a href="javascript:void(0);" onclick="toggle('source-honeybeex.revit', this);">Show source &equiv;</a></p>
  <div id="source-honeybeex.revit" class="source">
    <pre><code>"""Collection of functions for Revit."""
import config
from hbzone import HBZone
from hbsurface import HBSurface
from hbfensurface import HBFenSurface

import uuid


try:
    import clr
    clr.AddReference("RevitAPI")
    from Autodesk.Revit.DB import FilteredElementCollector, \
        BuiltInCategory, Options, Solid

    # objects for spatial calculation
    from Autodesk.Revit.DB import SpatialElementGeometryCalculator, \
        SpatialElementBoundaryOptions, SpatialElementBoundaryLocation

    clr.AddReference("RevitServices")
    from RevitServices.Persistence import DocumentManager

    clr.AddReference("RevitNodes")
    from Revit import GeometryConversion
    # Import ToProtoType, ToRevitType geometry conversion extension methods
    clr.ImportExtensions(GeometryConversion)

    clr.AddReference('ProtoGeometry')
    from Autodesk.DesignScript.Geometry import Point
except ImportError:
    "You can only use revit library from Revit not %s." % config.platform.platform


def collectRooms(document=None):
    """Collect all the rooms in the current Revit document."""
    if not document:
        document = DocumentManager.Instance.CurrentDBDocument
    collector = FilteredElementCollector(document)
    collector.OfCategory(BuiltInCategory.OST_Rooms)
    roomIter = collector.GetElementIdIterator()
    roomIter.Reset()
    return tuple(document.GetElement(elId) for elId in roomIter)


def collectMEPSpaces(document=None):
    """Collect all the spaces in the current Revit document."""
    if not document:
        document = DocumentManager.Instance.CurrentDBDocument
    collector = FilteredElementCollector(document)
    collector.OfCategory(BuiltInCategory.OST_MEPSpaces)
    roomIter = collector.GetElementIdIterator()
    roomIter.Reset()
    return tuple(document.GetElement(elId) for elId in roomIter)


def getChildElemenets(hostElement, addRectOpenings=True, includeShadows=False,
                      includeEmbeddedWalls=False,
                      includeSharedEmbeddedInserts=True):
    """Get child elemsts for a Revit element."""
    ids = hostElement.FindInserts(addRectOpenings,
                                  includeShadows,
                                  includeEmbeddedWalls,
                                  includeSharedEmbeddedInserts)

    return tuple(hostElement.Document.GetElement(i) for i in ids)


def extractPanelsVertices(hostElement, baseFace, opt):
    """Return lists of lists of vertices for a panel grid."""
    if not hostElement.CurtainGrid:
        return (), ()

    _panelElementIds = []
    _panelVertices = []

    for panelId in hostElement.CurtainGrid.GetPanelIds():

        _geo = hostElement.Document.GetElement(panelId).get_Geometry(opt)

        _outerFaces = (p.ToProtoType().Faces[1] for obj in _geo
                  for p in obj.GetInstanceGeometry())

        openings = (
            tuple(edge.StartVertex.PointGeometry for edge in loop.CoEdges)
            for _outerFace in _outerFaces
            for loop in _outerFace.Loops
            )

        coordinates = (
            tuple(
                tuple(baseFace.ClosestPointTo(pt) for pt in opening)
                for opening in openings
            ))

        filteredCoordinates = tuple(coorgroup if len(set(coorgroup)) > 2 else None
            for coorgroup in coordinates)

        _panelElementIds.append(panelId)
        _panelVertices.append(filteredCoordinates)

        # cleaning up
        (pt.Dispose() for opening in openings for pt in opening)
        (face.Dispose() for faceGroup in _outerFaces for face in faceGroup)


    return _panelElementIds, _panelVertices


def exctractGlazingVertices(hostElement, baseFace, opt):
    """Return glazing vertices for a window family instance.

    I was hoping that revit supports a cleaner way for doing this but for now
    I calculate the bounding box and find the face that it's vertices are coplanar
    with the host face.
    """
    # get 3d faces for the geometry
    # TODO: Take all the vertices for daylight modeling
    faces = (clr.Convert(obj, Solid).Faces
             for obj in hostElement.get_Geometry(opt))

    _outerFace = next(faces)[0].ToProtoType()[0]

    openings = (
        tuple(edge.StartVertex.PointGeometry for edge in loop.CoEdges)
        for face in _outerFace.Faces
        for loop in face.Loops[:-1]
    )

    coordinates = (
        tuple(
            tuple(baseFace.ClosestPointTo(pt) for pt in opening)
            for opening in openings
        ))

    # cleaning up
    (pt.Dispose() for opening in openings for pt in opening)
    (face.Dispose() for faceGroup in faces for face in faceGroup)

    filteredCoordinates = tuple(coorgroup if len(set(coorgroup)) > 2 else None
                                for coorgroup in coordinates)

    return filteredCoordinates


def createUUID():
    """Return a random uuid."""
    return str(uuid.uuid4())


def _getInternalElements(elements):
    """Get internal element from dynamo objects.

    This is similar to UnwrapElement in dynamo but will work fine outside dynamo.
    """
    if not elements:
        return

    if hasattr(elements, '__iter__'):
        return (_getInternalElements(x) for x in elements)
    elif hasattr(elements, 'InternalElement'):
        return elements.InternalElement
    else:
        return elements


def getBoundaryLocation(index=1):
    """Get SpatialElementBoundaryLocation.

    0 > Finish: Spatial element finish face.
    1 > Center: Spatial element centerline.
    """
    index = 1 if not index else index % 2

    _locations = (SpatialElementBoundaryLocation.Finish,
                  SpatialElementBoundaryLocation.Center)

    return _locations[index]


def getParameters(el, parameter):
    """Get the list of available parameter for an element."""
    return tuple(p.Definition.Name for p in el.Parameters)


def getParameter(el, parameter):
    """Get a parameter from an element."""
    return tuple(p.AsValueString() for p in el.Parameters \
                 if p.Definition.Name == parameter)[0]


def convertRoomsToHBZones(rooms, boundaryLocation=1):
    """Convert rooms to honeybee zones.

    This script will only work from inside Dynamo nodes. for a similar script
    forRrevit check this link for more details:
    https://github.com/jeremytammik/SpatialElementGeometryCalculator/
        blob/master/SpatialElementGeometryCalculator/Command.cs
    """
    rooms = tuple(_getInternalElements(rooms))
    if not rooms:
        return []

    # create a spatial element calculator to calculate room data
    doc = rooms[0].Document
    options = SpatialElementBoundaryOptions()
    options.SpatialElementBoundaryLocation = getBoundaryLocation(boundaryLocation)
    calculator = SpatialElementGeometryCalculator(doc, options)

    opt = Options()
    _ids = []
    _zones = range(len(rooms))
    _surfaces = {} # collect hbSurfaces so I can set adjucent surfaces
    for zoneCount, room in enumerate(rooms):
        # initiate zone based on room id
        _zone = HBZone(room.Id)

        # assert False, room.Id
        elementsData = calculator.CalculateSpatialElementGeometry(room)

        _roomGeo = elementsData.GetGeometry()
        # This can be the same as finish wall or in the center of the wall
        roomDSFaces = tuple(face.ToProtoType()[0] for face in _roomGeo.Faces)

        assert _roomGeo.Faces.Size == len(roomDSFaces), \
            "Number of rooms elements ({}) doesn't match number of faces ({}).\n" \
            "Make sure the Room is bounded.".format(_roomGeo.Faces.Size,
                                                    len(roomDSFaces))

        for count, face in enumerate(_roomGeo.Faces):
            # base face is useful to project the openings to room boundary
            _baseFace = roomDSFaces[count]

            # Revit is strange! if two roofs have a shared wall then it will be
            # duplicated! By checking the values inside the _collector
            _collector = []

            _boundaryFaces = elementsData.GetBoundaryFaceInfo(face)

            if len(_boundaryFaces) == 0:
                # initiate honeybee surface
                _ver = tuple(v.PointGeometry for v in _baseFace.Vertices)

                _hbSurface = HBSurface("%s:%s" % (_zone.name, createUUID()),
                                       _ver)

                _zone.addSurface(_hbSurface)
                continue

            for boundaryFace in _boundaryFaces:
                # boundaryFace is from type SpatialElementBoundarySubface
                # get the element (Wall, Roof, etc)
                boundaryElement = doc.GetElement(
                    boundaryFace.SpatialBoundaryElement.HostElementId
                )

                # initiate honeybee surface
                _ver = tuple(v.PointGeometry for v in _baseFace.Vertices)

                if _ver in _collector:
                    continue

                _hbSurface = HBSurface("%s:%s" % (_zone.name, boundaryElement.Id),
                                       _ver)

                _collector.append(_ver)

                if boundaryElement.Id not in _surfaces:
                    _surfaces[boundaryElement.Id] = _hbSurface
                else:
                    # TODO: set adjacent surface
                    pass

                # Take care of curtain wall systems
                # I'm not sure how this will work with custom Curtain Wall
                if getParameter(boundaryElement, 'Family') == 'Curtain Wall':
                    _elementIds, _coordinates = \
                        extractPanelsVertices(boundaryElement, _baseFace, opt)

                    for count, coordinate in enumerate(_coordinates):
                        if not coordinate:
                            print "{} has an opening with less than " \
                                "two coordinates. It has been removed!" \
                                .format(childElements[count].Id)
                            continue

                        # create honeybee surface - use element id as the name
                        _hbfenSurface = HBFenSurface(
                            _elementIds[count], coordinate)

                        # add fenestration surface to base honeybee surface
                        _hbSurface.addFenestrationSurface(_hbfenSurface)
                else:
                    # check if there is any child elements
                    childElements = getChildElemenets(boundaryElement)

                    if childElements:

                        _coordinates = exctractGlazingVertices(boundaryElement, _baseFace, opt)

                        for count, coordinate in enumerate(_coordinates):

                            if not coordinate:
                                print "{} has an opening with less than " \
                                    "two coordinates. It has been removed!" \
                                    .format(childElements[count].Id)
                                continue

                            # create honeybee surface - use element id as the name
                            _hbfenSurface = HBFenSurface(
                                childElements[count].Id, coordinate)
                            # add fenestration surface to base honeybee surface
                            _hbSurface.addFenestrationSurface(_hbfenSurface)

                # add hbsurface to honeybee zone
                _zone.addSurface(_hbSurface)
                boundaryElement.Dispose()

        _zones[zoneCount] = _zone

        # clean up!
        elementsData.Dispose()

    calculator.Dispose()
    return _zones
</code></pre>
  </div>

  </header>

  <section id="section-items">

    <h2 class="section-title" id="header-functions">Functions</h2>
      
  <div class="item">
    <div class="name def" id="honeybeex.revit.collectMEPSpaces">
    <p>def <span class="ident">collectMEPSpaces</span>(</p><p>document=None)</p>
    </div>
    

    
  
    <div class="desc"><p>Collect all the spaces in the current Revit document.</p></div>
  <div class="source_cont">
  <p class="source_link"><a href="javascript:void(0);" onclick="toggle('source-honeybeex.revit.collectMEPSpaces', this);">Show source &equiv;</a></p>
  <div id="source-honeybeex.revit.collectMEPSpaces" class="source">
    <pre><code>def collectMEPSpaces(document=None):
    """Collect all the spaces in the current Revit document."""
    if not document:
        document = DocumentManager.Instance.CurrentDBDocument
    collector = FilteredElementCollector(document)
    collector.OfCategory(BuiltInCategory.OST_MEPSpaces)
    roomIter = collector.GetElementIdIterator()
    roomIter.Reset()
    return tuple(document.GetElement(elId) for elId in roomIter)
</code></pre>
  </div>
</div>

  </div>
  
      
  <div class="item">
    <div class="name def" id="honeybeex.revit.collectRooms">
    <p>def <span class="ident">collectRooms</span>(</p><p>document=None)</p>
    </div>
    

    
  
    <div class="desc"><p>Collect all the rooms in the current Revit document.</p></div>
  <div class="source_cont">
  <p class="source_link"><a href="javascript:void(0);" onclick="toggle('source-honeybeex.revit.collectRooms', this);">Show source &equiv;</a></p>
  <div id="source-honeybeex.revit.collectRooms" class="source">
    <pre><code>def collectRooms(document=None):
    """Collect all the rooms in the current Revit document."""
    if not document:
        document = DocumentManager.Instance.CurrentDBDocument
    collector = FilteredElementCollector(document)
    collector.OfCategory(BuiltInCategory.OST_Rooms)
    roomIter = collector.GetElementIdIterator()
    roomIter.Reset()
    return tuple(document.GetElement(elId) for elId in roomIter)
</code></pre>
  </div>
</div>

  </div>
  
      
  <div class="item">
    <div class="name def" id="honeybeex.revit.convertRoomsToHBZones">
    <p>def <span class="ident">convertRoomsToHBZones</span>(</p><p>rooms, boundaryLocation=1)</p>
    </div>
    

    
  
    <div class="desc"><p>Convert rooms to honeybee zones.</p>
<p>This script will only work from inside Dynamo nodes. for a similar script
forRrevit check this link for more details:
https://github.com/jeremytammik/SpatialElementGeometryCalculator/
    blob/master/SpatialElementGeometryCalculator/Command.cs</p></div>
  <div class="source_cont">
  <p class="source_link"><a href="javascript:void(0);" onclick="toggle('source-honeybeex.revit.convertRoomsToHBZones', this);">Show source &equiv;</a></p>
  <div id="source-honeybeex.revit.convertRoomsToHBZones" class="source">
    <pre><code>def convertRoomsToHBZones(rooms, boundaryLocation=1):
    """Convert rooms to honeybee zones.

    This script will only work from inside Dynamo nodes. for a similar script
    forRrevit check this link for more details:
    https://github.com/jeremytammik/SpatialElementGeometryCalculator/
        blob/master/SpatialElementGeometryCalculator/Command.cs
    """
    rooms = tuple(_getInternalElements(rooms))
    if not rooms:
        return []

    # create a spatial element calculator to calculate room data
    doc = rooms[0].Document
    options = SpatialElementBoundaryOptions()
    options.SpatialElementBoundaryLocation = getBoundaryLocation(boundaryLocation)
    calculator = SpatialElementGeometryCalculator(doc, options)

    opt = Options()
    _ids = []
    _zones = range(len(rooms))
    _surfaces = {} # collect hbSurfaces so I can set adjucent surfaces
    for zoneCount, room in enumerate(rooms):
        # initiate zone based on room id
        _zone = HBZone(room.Id)

        # assert False, room.Id
        elementsData = calculator.CalculateSpatialElementGeometry(room)

        _roomGeo = elementsData.GetGeometry()
        # This can be the same as finish wall or in the center of the wall
        roomDSFaces = tuple(face.ToProtoType()[0] for face in _roomGeo.Faces)

        assert _roomGeo.Faces.Size == len(roomDSFaces), \
            "Number of rooms elements ({}) doesn't match number of faces ({}).\n" \
            "Make sure the Room is bounded.".format(_roomGeo.Faces.Size,
                                                    len(roomDSFaces))

        for count, face in enumerate(_roomGeo.Faces):
            # base face is useful to project the openings to room boundary
            _baseFace = roomDSFaces[count]

            # Revit is strange! if two roofs have a shared wall then it will be
            # duplicated! By checking the values inside the _collector
            _collector = []

            _boundaryFaces = elementsData.GetBoundaryFaceInfo(face)

            if len(_boundaryFaces) == 0:
                # initiate honeybee surface
                _ver = tuple(v.PointGeometry for v in _baseFace.Vertices)

                _hbSurface = HBSurface("%s:%s" % (_zone.name, createUUID()),
                                       _ver)

                _zone.addSurface(_hbSurface)
                continue

            for boundaryFace in _boundaryFaces:
                # boundaryFace is from type SpatialElementBoundarySubface
                # get the element (Wall, Roof, etc)
                boundaryElement = doc.GetElement(
                    boundaryFace.SpatialBoundaryElement.HostElementId
                )

                # initiate honeybee surface
                _ver = tuple(v.PointGeometry for v in _baseFace.Vertices)

                if _ver in _collector:
                    continue

                _hbSurface = HBSurface("%s:%s" % (_zone.name, boundaryElement.Id),
                                       _ver)

                _collector.append(_ver)

                if boundaryElement.Id not in _surfaces:
                    _surfaces[boundaryElement.Id] = _hbSurface
                else:
                    # TODO: set adjacent surface
                    pass

                # Take care of curtain wall systems
                # I'm not sure how this will work with custom Curtain Wall
                if getParameter(boundaryElement, 'Family') == 'Curtain Wall':
                    _elementIds, _coordinates = \
                        extractPanelsVertices(boundaryElement, _baseFace, opt)

                    for count, coordinate in enumerate(_coordinates):
                        if not coordinate:
                            print "{} has an opening with less than " \
                                "two coordinates. It has been removed!" \
                                .format(childElements[count].Id)
                            continue

                        # create honeybee surface - use element id as the name
                        _hbfenSurface = HBFenSurface(
                            _elementIds[count], coordinate)

                        # add fenestration surface to base honeybee surface
                        _hbSurface.addFenestrationSurface(_hbfenSurface)
                else:
                    # check if there is any child elements
                    childElements = getChildElemenets(boundaryElement)

                    if childElements:

                        _coordinates = exctractGlazingVertices(boundaryElement, _baseFace, opt)

                        for count, coordinate in enumerate(_coordinates):

                            if not coordinate:
                                print "{} has an opening with less than " \
                                    "two coordinates. It has been removed!" \
                                    .format(childElements[count].Id)
                                continue

                            # create honeybee surface - use element id as the name
                            _hbfenSurface = HBFenSurface(
                                childElements[count].Id, coordinate)
                            # add fenestration surface to base honeybee surface
                            _hbSurface.addFenestrationSurface(_hbfenSurface)

                # add hbsurface to honeybee zone
                _zone.addSurface(_hbSurface)
                boundaryElement.Dispose()

        _zones[zoneCount] = _zone

        # clean up!
        elementsData.Dispose()

    calculator.Dispose()
    return _zones
</code></pre>
  </div>
</div>

  </div>
  
      
  <div class="item">
    <div class="name def" id="honeybeex.revit.createUUID">
    <p>def <span class="ident">createUUID</span>(</p><p>)</p>
    </div>
    

    
  
    <div class="desc"><p>Return a random uuid.</p></div>
  <div class="source_cont">
  <p class="source_link"><a href="javascript:void(0);" onclick="toggle('source-honeybeex.revit.createUUID', this);">Show source &equiv;</a></p>
  <div id="source-honeybeex.revit.createUUID" class="source">
    <pre><code>def createUUID():
    """Return a random uuid."""
    return str(uuid.uuid4())
</code></pre>
  </div>
</div>

  </div>
  
      
  <div class="item">
    <div class="name def" id="honeybeex.revit.exctractGlazingVertices">
    <p>def <span class="ident">exctractGlazingVertices</span>(</p><p>hostElement, baseFace, opt)</p>
    </div>
    

    
  
    <div class="desc"><p>Return glazing vertices for a window family instance.</p>
<p>I was hoping that revit supports a cleaner way for doing this but for now
I calculate the bounding box and find the face that it's vertices are coplanar
with the host face.</p></div>
  <div class="source_cont">
  <p class="source_link"><a href="javascript:void(0);" onclick="toggle('source-honeybeex.revit.exctractGlazingVertices', this);">Show source &equiv;</a></p>
  <div id="source-honeybeex.revit.exctractGlazingVertices" class="source">
    <pre><code>def exctractGlazingVertices(hostElement, baseFace, opt):
    """Return glazing vertices for a window family instance.

    I was hoping that revit supports a cleaner way for doing this but for now
    I calculate the bounding box and find the face that it's vertices are coplanar
    with the host face.
    """
    # get 3d faces for the geometry
    # TODO: Take all the vertices for daylight modeling
    faces = (clr.Convert(obj, Solid).Faces
             for obj in hostElement.get_Geometry(opt))

    _outerFace = next(faces)[0].ToProtoType()[0]

    openings = (
        tuple(edge.StartVertex.PointGeometry for edge in loop.CoEdges)
        for face in _outerFace.Faces
        for loop in face.Loops[:-1]
    )

    coordinates = (
        tuple(
            tuple(baseFace.ClosestPointTo(pt) for pt in opening)
            for opening in openings
        ))

    # cleaning up
    (pt.Dispose() for opening in openings for pt in opening)
    (face.Dispose() for faceGroup in faces for face in faceGroup)

    filteredCoordinates = tuple(coorgroup if len(set(coorgroup)) > 2 else None
                                for coorgroup in coordinates)

    return filteredCoordinates
</code></pre>
  </div>
</div>

  </div>
  
      
  <div class="item">
    <div class="name def" id="honeybeex.revit.extractPanelsVertices">
    <p>def <span class="ident">extractPanelsVertices</span>(</p><p>hostElement, baseFace, opt)</p>
    </div>
    

    
  
    <div class="desc"><p>Return lists of lists of vertices for a panel grid.</p></div>
  <div class="source_cont">
  <p class="source_link"><a href="javascript:void(0);" onclick="toggle('source-honeybeex.revit.extractPanelsVertices', this);">Show source &equiv;</a></p>
  <div id="source-honeybeex.revit.extractPanelsVertices" class="source">
    <pre><code>def extractPanelsVertices(hostElement, baseFace, opt):
    """Return lists of lists of vertices for a panel grid."""
    if not hostElement.CurtainGrid:
        return (), ()

    _panelElementIds = []
    _panelVertices = []

    for panelId in hostElement.CurtainGrid.GetPanelIds():

        _geo = hostElement.Document.GetElement(panelId).get_Geometry(opt)

        _outerFaces = (p.ToProtoType().Faces[1] for obj in _geo
                  for p in obj.GetInstanceGeometry())

        openings = (
            tuple(edge.StartVertex.PointGeometry for edge in loop.CoEdges)
            for _outerFace in _outerFaces
            for loop in _outerFace.Loops
            )

        coordinates = (
            tuple(
                tuple(baseFace.ClosestPointTo(pt) for pt in opening)
                for opening in openings
            ))

        filteredCoordinates = tuple(coorgroup if len(set(coorgroup)) > 2 else None
            for coorgroup in coordinates)

        _panelElementIds.append(panelId)
        _panelVertices.append(filteredCoordinates)

        # cleaning up
        (pt.Dispose() for opening in openings for pt in opening)
        (face.Dispose() for faceGroup in _outerFaces for face in faceGroup)


    return _panelElementIds, _panelVertices
</code></pre>
  </div>
</div>

  </div>
  
      
  <div class="item">
    <div class="name def" id="honeybeex.revit.getBoundaryLocation">
    <p>def <span class="ident">getBoundaryLocation</span>(</p><p>index=1)</p>
    </div>
    

    
  
    <div class="desc"><p>Get SpatialElementBoundaryLocation.</p>
<p>0 &gt; Finish: Spatial element finish face.
1 &gt; Center: Spatial element centerline.</p></div>
  <div class="source_cont">
  <p class="source_link"><a href="javascript:void(0);" onclick="toggle('source-honeybeex.revit.getBoundaryLocation', this);">Show source &equiv;</a></p>
  <div id="source-honeybeex.revit.getBoundaryLocation" class="source">
    <pre><code>def getBoundaryLocation(index=1):
    """Get SpatialElementBoundaryLocation.

    0 > Finish: Spatial element finish face.
    1 > Center: Spatial element centerline.
    """
    index = 1 if not index else index % 2

    _locations = (SpatialElementBoundaryLocation.Finish,
                  SpatialElementBoundaryLocation.Center)

    return _locations[index]
</code></pre>
  </div>
</div>

  </div>
  
      
  <div class="item">
    <div class="name def" id="honeybeex.revit.getChildElemenets">
    <p>def <span class="ident">getChildElemenets</span>(</p><p>hostElement, addRectOpenings=True, includeShadows=False, includeEmbeddedWalls=False, includeSharedEmbeddedInserts=True)</p>
    </div>
    

    
  
    <div class="desc"><p>Get child elemsts for a Revit element.</p></div>
  <div class="source_cont">
  <p class="source_link"><a href="javascript:void(0);" onclick="toggle('source-honeybeex.revit.getChildElemenets', this);">Show source &equiv;</a></p>
  <div id="source-honeybeex.revit.getChildElemenets" class="source">
    <pre><code>def getChildElemenets(hostElement, addRectOpenings=True, includeShadows=False,
                      includeEmbeddedWalls=False,
                      includeSharedEmbeddedInserts=True):
    """Get child elemsts for a Revit element."""
    ids = hostElement.FindInserts(addRectOpenings,
                                  includeShadows,
                                  includeEmbeddedWalls,
                                  includeSharedEmbeddedInserts)

    return tuple(hostElement.Document.GetElement(i) for i in ids)
</code></pre>
  </div>
</div>

  </div>
  
      
  <div class="item">
    <div class="name def" id="honeybeex.revit.getParameter">
    <p>def <span class="ident">getParameter</span>(</p><p>el, parameter)</p>
    </div>
    

    
  
    <div class="desc"><p>Get a parameter from an element.</p></div>
  <div class="source_cont">
  <p class="source_link"><a href="javascript:void(0);" onclick="toggle('source-honeybeex.revit.getParameter', this);">Show source &equiv;</a></p>
  <div id="source-honeybeex.revit.getParameter" class="source">
    <pre><code>def getParameter(el, parameter):
    """Get a parameter from an element."""
    return tuple(p.AsValueString() for p in el.Parameters \
                 if p.Definition.Name == parameter)[0]
</code></pre>
  </div>
</div>

  </div>
  
      
  <div class="item">
    <div class="name def" id="honeybeex.revit.getParameters">
    <p>def <span class="ident">getParameters</span>(</p><p>el, parameter)</p>
    </div>
    

    
  
    <div class="desc"><p>Get the list of available parameter for an element.</p></div>
  <div class="source_cont">
  <p class="source_link"><a href="javascript:void(0);" onclick="toggle('source-honeybeex.revit.getParameters', this);">Show source &equiv;</a></p>
  <div id="source-honeybeex.revit.getParameters" class="source">
    <pre><code>def getParameters(el, parameter):
    """Get the list of available parameter for an element."""
    return tuple(p.Definition.Name for p in el.Parameters)
</code></pre>
  </div>
</div>

  </div>
  


  </section>

    </article>
  <div class="clear"> </div>
  <footer id="footer">
    <p>
      Documentation generated by
      <a href="https://github.com/BurntSushi/pdoc">pdoc 0.3.1</a>
    </p>

    <p>pdoc is in the public domain with the
      <a href="http://unlicense.org">UNLICENSE</a>
    </p>
  </footer>
</div>
<script>hljs.initHighlightingOnLoad();</script>
</body>
</html>
